#!/bin/bash

if [ -z "$1" ]; then
    git log --oneline --graph --decorate --all
elif [ "$1" = "--all" ] || [ "$1" = "-a" ]; then
    git log --oneline --graph --reflog
elif [ "$1" = "--date-order" ] || [ "$1" = "-a" ]; then
    git log --oneline --graph --reflog --date-order
elif [ "$1" = "update" ]; then
    if [ -z "$2" ]; then
        git remote update origin --prune
    else
        git remote update "$2" --prune
    fi
fi