#!/usr/bin/env bash

mkdir -p ~/.composer

docker run -it -v "$(pwd)":/src \
    -v "$HOME/.composer":/tmp/composer \
    -e COMPOSER_HOME=/tmp/composer \
    -w /src --net=host \
    -u $(id -u):$(id -g) php-with-composer composer $@
