#!/usr/bin/env bash

# docker run -it -v "$(pwd)":/src -w /src --net=host -u $(id -u):$(id -g) php:8.2-cli php "$@"
docker run -it -v "$(pwd)":/src -w /src --net=host -u $(id -u):$(id -g) php-with-composer php "$@"